repo: "https://raw.githubusercontent.com/YourGitHubUsername/your-plugin-repo/main"
github_token: "your_github_token_here"
loadables:
  example:
    jarName: "example"
    priority: 1
    enabled: true